// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type SharedTodo struct {
	ID          string
	Task        sql.NullString
	Description sql.NullString
	Done        sql.NullBool
	Important   sql.NullBool
	UserID      sql.NullString
	Date        sql.NullTime
	Time        sql.NullTime
	SharedBy    sql.NullString
}

type Team struct {
	ID       string
	Name     string
	Password string
	AdminID  string
}

type TeamMember struct {
	TeamID  string
	UserID  string
	IsAdmin sql.NullBool
}

type TeamTodo struct {
	ID          string
	Task        string
	Description sql.NullString
	Done        bool
	Important   sql.NullBool
	TeamID      string
	AssignedTo  sql.NullString
	Date        sql.NullTime
	Time        sql.NullTime
}

type Todo struct {
	ID          string
	Task        string
	Description sql.NullString
	Done        bool
	Important   bool
	UserID      sql.NullString
	Date        sql.NullTime
	Time        sql.NullTime
}

type User struct {
	ID       string
	Username string
	Password string
}
